repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
-   repo: https://github.com/digitalpulp/pre-commit-php
    rev: 1.4.0
    hooks:
    -   id: php-lint-all 
    -   id: php-lint
    -   id: php-unit
    -   id: php-cs
    -   id: php-cbf
    -   id: php-cs-fixer
    -   id: php-stan
-   repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.10
    hooks:
    -   id: validate-html
