name: MyStock continuous integrations

on:
  push:
    branches:
      - master
      - staging
      - MYL/*
  pull_request:
    branches:
      - master
      - staging
      - MYL/*
  workflow_dispatch:

jobs:
  build:
    name: Build MyStock
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install php
        uses: nanasess/setup-php@v4
        with:
          php-version: '8.2'

      - name: Install composer
        run: |
          sudo apt update
          sudo apt upgrade
