name: Require User Approval

on:
  push:
    branches:
      - master
      - staging
      - MYL/*
  pull_request:
    branches:
      - master
      - staging
      - MYL/*

jobs:
  require_user_approval:
    name: Require user approval
    runs_on: ubuntu-22.04
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        uses: BrianCArnold/require-user-approval@v0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: ..github/workflows/require_reviewers.yml
